"""
core/toolkit_data.py
Examination Prompt Toolkit — card data.
Organized by thinking objective, not AI capability.
"""

TOOLKIT_SECTIONS = [
    {
        "id": "mirror",
        "title": "Mirror Prompts",
        "objective": "Examine the Problem",
        "purpose": "Challenge the way the problem is currently understood before any solution is considered.",
        "room_color": "#0F1B2D",
        "accent": "#5B82B5",
        "accent_light": "#A8C4E0",
        "cards": [
            {
                "number": "01",
                "title": "Hidden Assumptions",
                "purpose": "Surface what is being taken for granted inside the problem statement.",
                "prompt": "Identify the assumptions that appear to be embedded in the following challenge. Separate assumptions from observable facts.",
                "why": "Most poor decisions begin with assumptions that were never recognized as assumptions.",
                "when": "Before defining the problem. Especially when the problem statement feels obvious.",
            },
            {
                "number": "02",
                "title": "Missing Information",
                "purpose": "Identify what would need to be known before responding with confidence.",
                "prompt": "What information would significantly increase confidence before deciding how to respond to this challenge?",
                "why": "Acting on incomplete information often produces solutions to the wrong problem.",
                "when": "When the pressure to decide is high but the evidence feels thin.",
            },
            {
                "number": "03",
                "title": "Alternative Framings",
                "purpose": "Reveal that the current problem framing is a choice, not a fact.",
                "prompt": "Give me five completely different ways this challenge could be framed without changing the underlying situation.",
                "why": "The frame you choose determines which solutions become visible and which remain invisible.",
                "when": "When proposed solutions all feel inadequate — the problem may be wrongly framed.",
            },
            {
                "number": "04",
                "title": "Blind Spot Finder",
                "purpose": "Introduce an outside perspective before committing to the current view.",
                "prompt": "If an experienced consultant were asked to critique this problem statement, what blind spots would they most likely identify?",
                "why": "Blind spots are invisible from the inside. A simulated outside perspective can surface them.",
                "when": "When you have been close to a problem for a long time and need a fresh angle.",
            },
            {
                "number": "05",
                "title": "Certainty Challenge",
                "purpose": "Distinguish between what is known and what is assumed.",
                "prompt": "Which parts of my current understanding appear well supported, and which parts rely primarily on assumptions?",
                "why": "Certainty that outpaces evidence is one of the most reliable precursors to poor decisions.",
                "when": "Before presenting a recommendation. Before allocating resources.",
            },
        ],
    },
    {
        "id": "human",
        "title": "Human Prompts",
        "objective": "Examine the People",
        "purpose": "Explore the perspectives, motivations, and resistances of everyone affected by the challenge.",
        "room_color": "#0D1F1A",
        "accent": "#3A9E7A",
        "accent_light": "#7ECFB0",
        "cards": [
            {
                "number": "06",
                "title": "Stakeholder Lens",
                "purpose": "Understand that different people experience the same situation differently.",
                "prompt": "Describe how each stakeholder would define this problem differently.",
                "why": "A solution that ignores how stakeholders frame the problem will face resistance even if it is technically correct.",
                "when": "Early in any initiative. Before designing engagement or communication strategies.",
            },
            {
                "number": "07",
                "title": "Resistance Explorer",
                "purpose": "Take resistance seriously as a signal rather than dismissing it as an obstacle.",
                "prompt": "Which stakeholder is most likely to resist the preferred solution, and why might that resistance actually be reasonable?",
                "why": "Resistance is often the most honest feedback available. It deserves examination, not management.",
                "when": "When a solution already has momentum and critical voices are being minimized.",
            },
            {
                "number": "08",
                "title": "Perspective Gap",
                "purpose": "Identify whose voice is missing from the current conversation.",
                "prompt": "Which stakeholder perspective is currently underrepresented in this discussion?",
                "why": "The perspective that is absent is often the one that would have changed the decision.",
                "when": "When a room of similar people has been doing most of the thinking.",
            },
            {
                "number": "09",
                "title": "Hidden Motivation",
                "purpose": "Look beneath stated positions to understand what people actually need.",
                "prompt": "What motivations might each stakeholder have that are not immediately visible?",
                "why": "People rarely share their real concerns in formal settings. Hidden motivations shape behaviour regardless.",
                "when": "When stakeholder behaviour seems inconsistent with their stated position.",
            },
            {
                "number": "10",
                "title": "Trust Builder",
                "purpose": "Understand what conditions must exist before genuine support is possible.",
                "prompt": "What conditions would need to exist before each stakeholder would genuinely support this initiative?",
                "why": "Compliance can be compelled. Trust cannot. Knowing the difference changes how you approach implementation.",
                "when": "Before launching any initiative that requires sustained human cooperation.",
            },
        ],
    },
    {
        "id": "possibility",
        "title": "Possibility Prompts",
        "objective": "Expand the Search Space",
        "purpose": "Widen the range of approaches under examination before any narrowing or decision-making begins.",
        "room_color": "#1A1408",
        "accent": "#C9A84C",
        "accent_light": "#E8D08A",
        "cards": [
            {
                "number": "11",
                "title": "Existing Path",
                "purpose": "Examine what is already available before searching for something new.",
                "prompt": "How could the current approach be improved before considering completely new alternatives?",
                "why": "New solutions carry implementation risk. Improving what exists is often faster, cheaper, and more durable.",
                "when": "Before committing to transformation. When incremental improvement may be sufficient.",
            },
            {
                "number": "12",
                "title": "Adjacent Industries",
                "purpose": "Borrow thinking from contexts that have solved similar problems differently.",
                "prompt": "How might organizations in completely different industries approach a similar challenge?",
                "why": "Industries develop blind spots. Adjacent industries often hold the solution that was invisible from inside.",
                "when": "When conventional approaches within your industry feel exhausted.",
            },
            {
                "number": "13",
                "title": "Contrarian Thinking",
                "purpose": "Give unconventional approaches a fair examination before dismissing them.",
                "prompt": "Suggest approaches that initially appear unreasonable but deserve examination before being dismissed.",
                "why": "The approaches that feel most unreasonable are often the ones that have never been seriously examined.",
                "when": "When the team is converging too quickly on the obvious answer.",
            },
            {
                "number": "14",
                "title": "Constraint Removal",
                "purpose": "Understand how constraints shape the available options.",
                "prompt": "If one major constraint disappeared tomorrow, how would the challenge change?",
                "why": "Constraints are often treated as permanent when they are temporary, negotiable, or self-imposed.",
                "when": "When the solution space feels artificially narrow.",
            },
            {
                "number": "15",
                "title": "Reverse Assumptions",
                "purpose": "Discover options that only become visible when assumptions are challenged.",
                "prompt": "Which assumptions, if reversed, would fundamentally change the available options?",
                "why": "Every assumption that goes unexamined silently eliminates a category of possible solutions.",
                "when": "After using the Mirror prompts to surface hidden assumptions.",
            },
        ],
    },
    {
        "id": "battlefield",
        "title": "Battlefield Prompts",
        "objective": "Stress-Test Thinking",
        "purpose": "Challenge selected ideas with firm, constructive scrutiny before any commitment is made.",
        "room_color": "#1F0D0D",
        "accent": "#C05050",
        "accent_light": "#E8A0A0",
        "cards": [
            {
                "number": "16",
                "title": "Strongest Critic",
                "purpose": "Hear the best version of the argument against your preferred direction.",
                "prompt": "Argue against my preferred direction as convincingly as possible.",
                "why": "If you cannot articulate the strongest case against your own position, you do not yet understand it well enough.",
                "when": "Before presenting a recommendation. Before committing resources.",
            },
            {
                "number": "17",
                "title": "Dangerous Assumption",
                "purpose": "Identify the assumption whose failure would cause the entire idea to collapse.",
                "prompt": "What assumption, if proven false, would cause this idea to fail?",
                "why": "Every idea rests on assumptions. The most dangerous are the ones that feel most certain.",
                "when": "After selecting an approach but before implementation planning begins.",
            },
            {
                "number": "18",
                "title": "Missing Condition",
                "purpose": "Identify what must be true for this idea to succeed — and whether it currently is.",
                "prompt": "What condition must exist for this idea to succeed but is currently absent?",
                "why": "Ideas fail not because they are wrong in theory but because the conditions for success were not in place.",
                "when": "During implementation planning. When an idea that worked elsewhere is being transplanted.",
            },
            {
                "number": "19",
                "title": "Failure Simulation",
                "purpose": "Work backwards from failure to identify risks that forward planning misses.",
                "prompt": "Imagine this initiative failed after twelve months. Explain the most likely reasons.",
                "why": "Pre-mortem thinking surfaces failure modes that optimism systematically conceals.",
                "when": "Before finalizing an implementation plan. When confidence is high.",
            },
            {
                "number": "20",
                "title": "Executive Challenge",
                "purpose": "Anticipate the hardest questions before they are asked in a high-stakes setting.",
                "prompt": "What difficult questions would an experienced executive ask before approving this proposal?",
                "why": "Preparing for the hardest questions is more valuable than rehearsing the easy ones.",
                "when": "Before presenting to senior leadership. Before any high-stakes approval process.",
            },
        ],
    },
    {
        "id": "future",
        "title": "Future Prompts",
        "objective": "Examine Consequences",
        "purpose": "Map what happens next — including the outcomes that are unlikely to appear in any plan.",
        "room_color": "#12101F",
        "accent": "#6B5DB5",
        "accent_light": "#B0A8E0",
        "cards": [
            {
                "number": "21",
                "title": "Ripple Effects",
                "purpose": "Look beyond first-order consequences to what they in turn produce.",
                "prompt": "What second-order and third-order consequences might emerge if this solution succeeds?",
                "why": "Most plans account for first-order effects. Second and third-order effects are where surprises live.",
                "when": "After selecting a direction. Before finalizing an implementation plan.",
            },
            {
                "number": "22",
                "title": "Hidden Costs",
                "purpose": "Surface the costs that will not appear in any budget until it is too late.",
                "prompt": "Which costs are least visible today but most likely to appear later?",
                "why": "Visible costs are managed. Hidden costs are experienced. They are rarely the same list.",
                "when": "During resource planning. When a proposal looks financially attractive.",
            },
            {
                "number": "23",
                "title": "Early Signals",
                "purpose": "Define what failure looks like early enough to do something about it.",
                "prompt": "What indicators should we monitor that would suggest this initiative is beginning to fail?",
                "why": "Early signals of failure are almost always present. They are simply not being watched for.",
                "when": "Before launch. When designing governance or monitoring frameworks.",
            },
            {
                "number": "24",
                "title": "Unintended Outcomes",
                "purpose": "Anticipate consequences that no one planned for — positive or negative.",
                "prompt": "What positive or negative consequences are most likely to be overlooked?",
                "why": "The consequences most worth examining are the ones that do not appear in official plans.",
                "when": "When a solution has strong internal support and critical scrutiny has been minimal.",
            },
            {
                "number": "25",
                "title": "Twelve-Month Reflection",
                "purpose": "Use future hindsight to reveal present blind spots.",
                "prompt": "Imagine we are one year in the future. What would we wish we had examined more carefully before making this decision?",
                "why": "The question we wish we had asked is almost always knowable in advance — if we make time to ask it.",
                "when": "Before any significant commitment. At the end of a thinking session.",
            },
        ],
    },
    {
        "id": "studio",
        "title": "Studio Prompts",
        "objective": "The Doctrine in Practice",
        "purpose": "These prompts belong to no single room. They exist to protect the quality of examination itself.",
        "room_color": "#0D1117",
        "accent": "#C9A84C",
        "accent_light": "#E8D08A",
        "cards": [
            {
                "number": "S1",
                "title": "Conditions Before Conviction",
                "purpose": "Ensure that any recommendation rests on examined conditions, not confidence.",
                "prompt": "Before recommending any course of action, identify the conditions that would need to be true for that recommendation to be appropriate.",
                "why": "Conviction without examined conditions is not confidence — it is exposure.",
                "when": "Before any recommendation is made. Before any conclusion is presented as settled.",
            },
            {
                "number": "S2",
                "title": "Examination Quality",
                "purpose": "Assess how thoroughly the challenge has actually been examined.",
                "prompt": "Which parts of this challenge have been thoroughly examined, and which parts deserve further examination before any decision is made?",
                "why": "The feeling of having examined something thoroughly is not the same as having done so.",
                "when": "At the end of any thinking session. Before closing a decision.",
            },
            {
                "number": "S3",
                "title": "False Confidence Detector",
                "purpose": "Identify where the strength of a conclusion exceeds the strength of its evidence.",
                "prompt": "Which conclusions currently appear stronger than the available evidence actually supports?",
                "why": "False confidence is invisible from the inside. It requires a deliberate prompt to surface.",
                "when": "When a group has reached strong consensus quickly. When dissent has been minimal.",
            },
            {
                "number": "S4",
                "title": "Slow Me Down",
                "purpose": "Resist the pressure to decide before examination is complete.",
                "prompt": "What questions should I answer before feeling confident enough to make this decision?",
                "why": "Speed of decision is rarely the limiting factor in organizational success. Quality of examination usually is.",
                "when": "When urgency is being used to compress thinking time. When a deadline feels artificial.",
            },
            {
                "number": "S5",
                "title": "Thinking Integrity",
                "purpose": "Test a recommendation against the scrutiny of diverse expertise.",
                "prompt": "If this recommendation were challenged by five experts from different disciplines, what concerns might each of them raise?",
                "why": "A recommendation that cannot survive multidisciplinary scrutiny is not ready to be made.",
                "when": "Before presenting any significant recommendation to decision-makers.",
            },
        ],
    },
]
